# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    indices:
        - name: articles
          class: App\Entity\Articles

        - name: posts
          class: App\Entity\Posts

    doctrineSubscribedEvents: ['postPersist', 'postUpdate', 'preRemove']
